version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/thebluefowl/gologger"
  dependencies_vendored = false

[[analyzers]]
name = "secrets"
enabled = true